//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZSProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class calculation
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> log_id { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<int> remaining_time { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
